export const mockCities = [
  {
    _id: 'city-mumbai',
    name: 'Mumbai',
    country: 'India',
    region: 'Maharashtra',
    description: 'The financial capital of India, known for Bollywood, Gateway of India, and street food.',
    image: 'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=800',
    costIndex: 3,
    popularity: 95,
    avgDailyCost: 3500,
    tags: ['city', 'food', 'culture', 'nightlife'],
    bestMonths: ['Nov', 'Dec', 'Jan', 'Feb'],
  },
  {
    _id: 'city-goa',
    name: 'Goa',
    country: 'India',
    region: 'Goa',
    description: 'Famous for its beaches, Portuguese heritage, seafood, and vibrant nightlife.',
    image: 'https://images.unsplash.com/photo-1587922546307-776227941871?w=800',
    costIndex: 2,
    popularity: 92,
    avgDailyCost: 2500,
    tags: ['beach', 'nightlife', 'food', 'adventure'],
    bestMonths: ['Nov', 'Dec', 'Jan', 'Feb'],
  },
  {
    _id: 'city-jaipur',
    name: 'Jaipur',
    country: 'India',
    region: 'Rajasthan',
    description: 'The Pink City, famous for its stunning Rajput palaces, forts, and vibrant bazaars.',
    image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800',
    costIndex: 2,
    popularity: 88,
    avgDailyCost: 2000,
    tags: ['history', 'culture', 'shopping'],
    bestMonths: ['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'],
  },
  {
    _id: 'city-paris',
    name: 'Paris',
    country: 'France',
    region: 'Europe',
    description: 'The City of Light, famous for its art, fashion, gastronomy, and the iconic Eiffel Tower.',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800',
    costIndex: 5,
    popularity: 98,
    avgDailyCost: 9500,
    tags: ['iconic', 'art', 'romance', 'shopping'],
    bestMonths: ['May', 'Jun', 'Jul', 'Aug', 'Sep'],
  },
  {
    _id: 'city-tokyo',
    name: 'Tokyo',
    country: 'Japan',
    region: 'East Asia',
    description: 'A neon-lit metropolis combining ultra-modern tech with historic Shinto temples.',
    image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800',
    costIndex: 4,
    popularity: 97,
    avgDailyCost: 7500,
    tags: ['city', 'food', 'tech', 'culture'],
    bestMonths: ['Mar', 'Apr', 'May', 'Oct', 'Nov'],
  },
  {
    _id: 'city-bali',
    name: 'Bali',
    country: 'Indonesia',
    region: 'Southeast Asia',
    description: 'The Island of the Gods, renowned for forested volcanic mountains, beaches, and coral reefs.',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
    costIndex: 1,
    popularity: 94,
    avgDailyCost: 1500,
    tags: ['beach', 'nature', 'culture', 'adventure'],
    bestMonths: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'],
  }
];

export const mockActivities = [
  {
    _id: 'act-gateway',
    name: 'Gateway of India Tour',
    city: { _id: 'city-mumbai', name: 'Mumbai', country: 'India' },
    category: 'sightseeing',
    estimatedCost: 0,
    duration: { value: 2, unit: 'hours' },
    description: 'Iconic British-built triumphal arch overlooking the Arabian Sea. Best at sunrise.',
    rating: { average: 4.5, count: 120 },
    image: 'https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?w=600',
    tags: ['monument', 'history'],
  },
  {
    _id: 'act-streetfood',
    name: 'Street Food Tour - Chowpatty',
    city: { _id: 'city-mumbai', name: 'Mumbai', country: 'India' },
    category: 'food',
    estimatedCost: 500,
    duration: { value: 3, unit: 'hours' },
    description: 'Bhel puri, vada pav, and pav bhaji at the famous Chowpatty beach.',
    rating: { average: 4.7, count: 89 },
    image: 'https://images.unsplash.com/photo-1567337710282-00832b415979?w=600',
    tags: ['street food', 'local'],
  },
  {
    _id: 'act-bagabeach',
    name: 'Baga Beach Water Sports',
    city: { _id: 'city-goa', name: 'Goa', country: 'India' },
    category: 'adventure',
    estimatedCost: 1500,
    duration: { value: 6, unit: 'hours' },
    description: 'Sun, sand, and high-speed water sports – parasailing, banana boat, and jet skiing.',
    rating: { average: 4.6, count: 210 },
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600',
    tags: ['beach', 'water sports'],
  },
  {
    _id: 'act-churchgoa',
    name: 'Old Goa Church Tour',
    city: { _id: 'city-goa', name: 'Goa', country: 'India' },
    category: 'culture',
    estimatedCost: 200,
    duration: { value: 3, unit: 'hours' },
    description: 'UNESCO-listed Basilica of Bom Jesus and Se Cathedral – finest Portuguese baroque architecture.',
    rating: { average: 4.4, count: 78 },
    image: 'https://images.unsplash.com/photo-1583416750470-965b2707b355?w=600',
    tags: ['history', 'architecture'],
  },
  {
    _id: 'act-amberfort',
    name: 'Amber Fort Elephant Tour',
    city: { _id: 'city-jaipur', name: 'Jaipur', country: 'India' },
    category: 'sightseeing',
    estimatedCost: 500,
    duration: { value: 3, unit: 'hours' },
    description: 'Majestic hilltop fort with mirrored rooms, gardens, and panoramic views of Maota Lake.',
    rating: { average: 4.8, count: 320 },
    image: 'https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?w=600',
    tags: ['fort', 'history'],
  },
  {
    _id: 'act-hawamahal',
    name: 'Hawa Mahal Photo Walk',
    city: { _id: 'city-jaipur', name: 'Jaipur', country: 'India' },
    category: 'sightseeing',
    estimatedCost: 100,
    duration: { value: 1, unit: 'hours' },
    description: 'The Palace of Winds – iconic 5-story pink sandstone facade with 953 small windows.',
    rating: { average: 4.5, count: 280 },
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600',
    tags: ['architecture', 'photography'],
  },
  {
    _id: 'act-eiffel',
    name: 'Eiffel Tower Sunset Visit',
    city: { _id: 'city-paris', name: 'Paris', country: 'France' },
    category: 'sightseeing',
    estimatedCost: 2800,
    duration: { value: 2, unit: 'hours' },
    description: 'Enjoy sweeping panoramic views of Paris from the second or third floor at sunset.',
    rating: { average: 4.9, count: 890 },
    image: 'https://images.unsplash.com/photo-1543349689-9a4d426bee8e?w=600',
    tags: ['iconic', 'sunset', 'views'],
  },
  {
    _id: 'act-louvre',
    name: 'Louvre Guided Tour',
    city: { _id: 'city-paris', name: 'Paris', country: 'France' },
    category: 'culture',
    estimatedCost: 2200,
    duration: { value: 4, unit: 'hours' },
    description: 'Skip the line and explore historic masterpieces including the Mona Lisa and Venus de Milo.',
    rating: { average: 4.8, count: 720 },
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600',
    tags: ['art', 'museum'],
  },
  {
    _id: 'act-shibuya',
    name: 'Shibuya Crossing Photography',
    city: { _id: 'city-tokyo', name: 'Tokyo', country: 'Japan' },
    category: 'entertainment',
    estimatedCost: 0,
    duration: { value: 1, unit: 'hours' },
    description: 'Walk the world\'s busiest pedestrian intersection and capture high-action night photography.',
    rating: { average: 4.7, count: 560 },
    image: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=600',
    tags: ['iconic', 'photography'],
  },
  {
    _id: 'act-riceterrace',
    name: 'Ubud Rice Terrace Trek',
    city: { _id: 'city-bali', name: 'Bali', country: 'Indonesia' },
    category: 'nature',
    estimatedCost: 400,
    duration: { value: 3, unit: 'hours' },
    description: 'Hike through the lush, scenic emerald rice terraces of Tegallalang with a local guide.',
    rating: { average: 4.8, count: 340 },
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600',
    tags: ['nature', 'trekking'],
  }
];

export const mockTrips = [
  {
    _id: 'trip-1',
    name: 'Golden Triangle Adventure',
    description: 'Explore the iconic Delhi-Agra-Jaipur triangle – the best of North India in 7 days.',
    startDate: '2026-10-15',
    endDate: '2026-10-21',
    budget: 50000,
    currency: 'INR',
    status: 'planning',
    isPublic: true,
    coverPhoto: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=1200',
    tags: ['india', 'history', 'culture'],
    stops: [
      {
        _id: 'stop-1a',
        trip: 'trip-1',
        city: {
          _id: 'city-jaipur',
          name: 'Jaipur',
          country: 'India',
          image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800'
        },
        customCityName: '',
        arrivalDate: '2026-10-15',
        departureDate: '2026-10-18',
        notes: 'Explore the forts and local bazaars.',
        order: 0,
        accommodation: {
          name: 'Rajputana Sheraton',
          address: 'Palace Road, Jaipur',
          cost: 15000
        },
        activities: [
          {
            _id: 'trip-act-1',
            tripStop: 'stop-1a',
            trip: 'trip-1',
            activity: {
              _id: 'act-amberfort',
              name: 'Amber Fort Elephant Tour',
              category: 'sightseeing',
              estimatedCost: 500,
              duration: { value: 3, unit: 'hours' },
              image: 'https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?w=600'
            },
            customName: '',
            customDescription: '',
            customCost: 0,
            scheduledDate: '2026-10-16',
            startTime: '09:00',
            endTime: '12:00',
            status: 'planned',
            order: 0,
            notes: 'Wear comfortable shoes.'
          },
          {
            _id: 'trip-act-2',
            tripStop: 'stop-1a',
            trip: 'trip-1',
            activity: {
              _id: 'act-hawamahal',
              name: 'Hawa Mahal Photo Walk',
              category: 'sightseeing',
              estimatedCost: 100,
              duration: { value: 1, unit: 'hours' },
              image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600'
            },
            customName: '',
            customDescription: '',
            customCost: 0,
            scheduledDate: '2026-10-17',
            startTime: '16:00',
            endTime: '17:00',
            status: 'planned',
            order: 1,
            notes: 'Take photos from the rooftop cafe opposite.'
          }
        ]
      },
      {
        _id: 'stop-1b',
        trip: 'trip-1',
        city: {
          _id: 'city-goa',
          name: 'Goa',
          country: 'India',
          image: 'https://images.unsplash.com/photo-1587922546307-776227941871?w=800'
        },
        customCityName: '',
        arrivalDate: '2026-10-18',
        departureDate: '2026-10-21',
        notes: 'Chill by the beach side.',
        order: 1,
        accommodation: {
          name: 'Taj Exotica',
          address: 'Benaulim, Goa',
          cost: 20000
        },
        activities: [
          {
            _id: 'trip-act-3',
            tripStop: 'stop-1b',
            trip: 'trip-1',
            activity: {
              _id: 'act-bagabeach',
              name: 'Baga Beach Water Sports',
              category: 'adventure',
              estimatedCost: 1500,
              duration: { value: 6, unit: 'hours' },
              image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600'
            },
            customName: '',
            customDescription: '',
            customCost: 0,
            scheduledDate: '2026-10-19',
            startTime: '10:00',
            endTime: '16:00',
            status: 'planned',
            order: 0,
            notes: 'Bring extra clothes.'
          }
        ]
      }
    ]
  }
];
